// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD17emurIRH_1-0hHYV1Pw7cWXmhbuBtoI',
    appId: '1:92944010293:web:7c149bd10798439a4e357c',
    messagingSenderId: '92944010293',
    projectId: 'shade-craft',
    authDomain: 'shade-craft.firebaseapp.com',
    storageBucket: 'shade-craft.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl1S1phhh_pptThovV7AHZm5GXBYYx46M',
    appId: '1:92944010293:android:5502bf968a08fb614e357c',
    messagingSenderId: '92944010293',
    projectId: 'shade-craft',
    storageBucket: 'shade-craft.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPqJFAizH6lic3_kJ7uj72L3x4KyTf0MY',
    appId: '1:92944010293:ios:9e6306258b6dbd794e357c',
    messagingSenderId: '92944010293',
    projectId: 'shade-craft',
    storageBucket: 'shade-craft.firebasestorage.app',
    iosBundleId: 'com.example.shadeCraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPqJFAizH6lic3_kJ7uj72L3x4KyTf0MY',
    appId: '1:92944010293:ios:9e6306258b6dbd794e357c',
    messagingSenderId: '92944010293',
    projectId: 'shade-craft',
    storageBucket: 'shade-craft.firebasestorage.app',
    iosBundleId: 'com.example.shadeCraft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD17emurIRH_1-0hHYV1Pw7cWXmhbuBtoI',
    appId: '1:92944010293:web:195cd0433dcdabaf4e357c',
    messagingSenderId: '92944010293',
    projectId: 'shade-craft',
    authDomain: 'shade-craft.firebaseapp.com',
    storageBucket: 'shade-craft.firebasestorage.app',
  );
}
